# Generated by Django 5.0.3 on 2024-04-18 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_table',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='order_table',
            name='orderedProduct_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_id', to='base.products_table'),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='orderedProduct_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_name', to='base.products_table'),
        ),
    ]
