# Generated by Django 5.0.3 on 2024-04-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_products_table_alter_order_table_orderedproduct_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_table',
        ),
    ]
