# Generated by Django 5.0.3 on 2024-04-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
