# Generated by Django 5.0.3 on 2024-04-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.products_table')),
            ],
        ),
        migrations.DeleteModel(
            name='Order_table',
        ),
    ]
